import React, { useState, useEffect } from 'react';
import { useLocation, Link, useNavigate } from 'react-router-dom';
import { 
  Sparkles, 
  Calendar, 
  MapPin, 
  IndianRupee, 
  Clock, 
  Tag, 
  Lightbulb, 
  ArrowRight, 
  Download, 
  Share2, 
  Hotel, 
  QrCode, 
  ChevronDown, 
  ChevronUp,
  Activity,
  CheckCircle,
  Navigation,
  FileText,
  Loader2
} from 'lucide-react';
import { generateAITripPlan } from '../services/aiService';
import TrafficBadge from '../components/TrafficBadge';
import { exportItineraryToPDF } from '../services/pdfExportService';

export default function ItineraryPage() {
  const locationState = useLocation().state;
  const navigate = useNavigate();

  const [plan, setPlan] = useState(locationState?.plan || null);
  const [activeDay, setActiveDay] = useState(1);
  const [loading, setLoading] = useState(!locationState?.plan);
  const [exportingPdf, setExportingPdf] = useState(false);

  useEffect(() => {
    if (!plan) {
      setLoading(true);
      generateAITripPlan({
        budget: 12000,
        days: 3,
        interests: ['temples', 'food', 'nature'],
        location: 'Jaipur, Rajasthan',
        travelStyle: 'balanced'
      }).then((generatedPlan) => {
        setPlan(generatedPlan);
        setLoading(false);
      });
    }
  }, [plan]);

  if (loading || !plan) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center space-y-4">
        <div className="w-12 h-12 rounded-2xl bg-[#E8F8ED] border border-[#BDE8C7] flex items-center justify-center text-[#22A45D] animate-spin">
          <Sparkles className="w-6 h-6" />
        </div>
        <p className="text-[#1A2E22] font-bold text-sm">YatraSense is compiling your day-by-day schedule...</p>
      </div>
    );
  }

  const currentDayData = plan.itinerary.find((d) => d.dayNumber === activeDay) || plan.itinerary[0];

  const handleExportPDF = async () => {
    try {
      setExportingPdf(true);
      await exportItineraryToPDF(plan);
    } catch (err) {
      console.error('PDF export failed, falling back to window.print():', err);
      window.print();
    } finally {
      setExportingPdf(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* Top Meta Header & Actions */}
      <div className="glass-panel-glow bg-white rounded-3xl p-6 sm:p-8 border border-[#B8E4B5] space-y-6 shadow-md">
        
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 pb-6 border-b border-[#D8ECD6]">
          <div>
            <div className="flex items-center space-x-2">
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase tracking-wider bg-[#E8F8ED] text-[#1D8E50] border border-[#BDE8C7]">
                Trip ID: {plan.tripId}
              </span>
              <span className="text-[#718778] text-xs font-semibold">• Generated by YatraSense</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-[#1A2E22] mt-1">
              {plan.meta.location}
            </h1>
            <p className="text-[#4E5E54] text-xs mt-0.5 font-medium">
              {plan.meta.days} Days • Focus: {plan.meta.interests.join(', ')}
            </p>
          </div>

          {/* Action CTAs */}
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={handleExportPDF}
              disabled={exportingPdf}
              className={`px-3.5 py-2 rounded-xl border text-xs font-bold flex items-center space-x-1.5 transition-all shadow-xs ${
                exportingPdf
                  ? 'bg-slate-100 text-slate-400 border-slate-200 cursor-wait'
                  : 'bg-[#F4FBF3] hover:bg-[#E8F8ED] text-[#1A2E22] border-[#D8ECD6]'
              }`}
            >
              {exportingPdf ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 text-[#22A45D] animate-spin" />
                  <span>Generating PDF...</span>
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5 text-[#22A45D]" />
                  <span>Export PDF</span>
                </>
              )}
            </button>
            
            <Link
              to={`/pass?tripId=${encodeURIComponent(plan.tripId)}&destination=${encodeURIComponent(plan.meta.location)}&days=${plan.meta.days}`}
              state={{ tripId: plan.tripId, destination: plan.meta.location, days: plan.meta.days }}
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-bold flex items-center space-x-1.5 shadow-md shadow-purple-600/25 transition-all"
            >
              <QrCode className="w-3.5 h-3.5" />
              <span>Get Digital Tourist Pass</span>
            </Link>

            <Link
              to={`/hotels?location=${encodeURIComponent(plan.meta.location)}`}
              state={{ location: plan.meta.location }}
              className="px-4 py-2 rounded-xl bg-[#22A45D] hover:bg-[#1D8E50] text-white text-xs font-bold flex items-center space-x-1.5 shadow-md shadow-[#22A45D]/25 transition-all"
            >
              <Hotel className="w-3.5 h-3.5" />
              <span>Recommended Hotels</span>
            </Link>
          </div>
        </div>

        {/* Quick Budget & Metric Summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-3.5 rounded-2xl bg-[#F4FBF3] border border-[#D8ECD6]">
            <p className="text-[11px] text-[#4E5E54] font-semibold">Allocated Budget</p>
            <p className="text-lg font-extrabold text-[#1A2E22] font-mono mt-0.5">
              ₹{plan.meta.budget?.toLocaleString('en-IN')}
            </p>
          </div>
          
          <div className="p-3.5 rounded-2xl bg-[#F4FBF3] border border-[#D8ECD6]">
            <p className="text-[11px] text-[#4E5E54] font-semibold">Estimated Total Spend</p>
            <p className="text-lg font-extrabold text-[#1D8E50] font-mono mt-0.5">
              ₹{plan.meta.calculatedEstimate?.toLocaleString('en-IN')}
            </p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F4FBF3] border border-[#D8ECD6]">
            <p className="text-[11px] text-[#4E5E54] font-semibold">Projected Buffer / Savings</p>
            <p className="text-lg font-extrabold text-[#22A45D] font-mono mt-0.5">
              ₹{plan.meta.savings?.toLocaleString('en-IN')}
            </p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F4FBF3] border border-[#D8ECD6]">
            <p className="text-[11px] text-[#4E5E54] font-semibold">IoT Crowd Optimization</p>
            <p className="text-xs font-bold text-[#1D8E50] mt-1 flex items-center space-x-1">
              <CheckCircle className="w-3.5 h-3.5 text-[#22A45D]" />
              <span>Active & Staggered</span>
            </p>
          </div>
        </div>

      </div>

      {/* Day Selector Tabs */}
      <div className="flex items-center space-x-2 overflow-x-auto pb-2">
        {plan.itinerary.map((day) => (
          <button
            key={day.dayNumber}
            onClick={() => setActiveDay(day.dayNumber)}
            className={`px-5 py-2.5 rounded-xl font-bold text-xs whitespace-nowrap transition-all flex items-center space-x-2 border ${
              activeDay === day.dayNumber
                ? 'bg-[#22A45D] text-white border-[#1D8E50] shadow-md shadow-[#22A45D]/25'
                : 'bg-white text-[#1A2E22] border-[#D8ECD6] hover:bg-[#F1F8F0]'
            }`}
          >
            <Calendar className="w-3.5 h-3.5" />
            <span>Day {day.dayNumber}</span>
          </button>
        ))}
      </div>

      {/* Active Day Detailed Itinerary Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left 2 Cols: Activity Timeline */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between pb-2">
            <div>
              <h2 className="text-xl font-extrabold text-[#1A2E22]">
                {currentDayData.dayTitle}
              </h2>
              <p className="text-xs text-[#4E5E54] mt-0.5 font-medium">{currentDayData.aiInsight}</p>
            </div>
          </div>

          {/* Hotel to First Stop Traffic Header */}
          {currentDayData.activities && currentDayData.activities.length > 0 && (
            <div className="p-3.5 rounded-2xl bg-[#F4FBF3] border border-[#BDE8C7] flex flex-col sm:flex-row sm:items-center justify-between gap-2 shadow-xs">
              <div className="flex items-center space-x-2 text-xs text-[#1A2E22] font-semibold">
                <Hotel className="w-4 h-4 text-[#22A45D]" />
                <span>Hotel Departure &rarr; {currentDayData.activities[0].name}</span>
              </div>
              <TrafficBadge 
                origin={`Recommended Hotel in ${plan.meta.location}`} 
                destination={`${currentDayData.activities[0].name}, ${plan.meta.location}`} 
                compact={false} 
              />
            </div>
          )}

          {/* Timeline Cards */}
          <div className="space-y-4 relative before:absolute before:inset-0 before:left-5 before:w-0.5 before:bg-[#D8ECD6]">
            {currentDayData.activities.map((act, index) => {
              const nextAct = currentDayData.activities[index + 1];
              return (
                <div key={act.id || index} className="space-y-3">
                  <div className="relative pl-12">
                    
                    {/* Step Circle Indicator */}
                    <div className="absolute left-2.5 top-5 -translate-x-1/2 w-6 h-6 rounded-full bg-white border-2 border-[#22A45D] flex items-center justify-center text-[10px] font-extrabold text-[#1D8E50] shadow-sm">
                      {index + 1}
                    </div>

                    {/* Activity Card */}
                    <div className="glass-card p-5 rounded-2xl space-y-3 border border-[#D8ECD6]">
                      
                      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                        <h3 className="text-base font-bold text-[#1A2E22]">
                          {act.name}
                        </h3>
                        <span className="text-xs font-mono font-bold text-[#1D8E50] bg-[#E8F8ED] px-2.5 py-1 rounded-lg border border-[#BDE8C7] self-start sm:self-auto">
                          ₹{act.cost} est. entry
                        </span>
                      </div>

                      <div className="flex flex-wrap items-center gap-3 text-xs text-[#4E5E54]">
                        <span className="flex items-center space-x-1 font-semibold text-[#1A2E22]">
                          <Clock className="w-3.5 h-3.5 text-[#22A45D]" />
                          <span>{act.time}</span>
                        </span>
                        <span className="flex items-center space-x-1">
                          <Tag className="w-3.5 h-3.5 text-[#718778]" />
                          <span>{act.category}</span>
                        </span>
                        <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-[#E8F8ED] text-[#1D8E50] border border-[#BDE8C7]">
                          🟢 Optimal Slot: Low Footfall
                        </span>
                      </div>

                      {/* AI Insider Tip */}
                      <div className="p-3 rounded-xl bg-[#F4FBF3] border border-[#D8ECD6] text-xs text-[#1A2E22] flex items-start space-x-2">
                        <Lightbulb className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                        <div>
                          <strong className="text-amber-800">AI Tip:</strong> {act.tip}
                        </div>
                      </div>

                      {/* Transport suggestion */}
                      {act.transportSuggestion && (
                        <div className="text-[11px] text-[#4E5E54] font-medium flex items-center space-x-1.5 pt-1 border-t border-[#D8ECD6]">
                          <Navigation className="w-3.5 h-3.5 text-[#22A45D]" />
                          <span>Transit: {act.transportSuggestion}</span>
                        </div>
                      )}

                    </div>
                  </div>

                  {/* Inter-Stop Live Traffic Connector */}
                  {nextAct && (
                    <div className="pl-12 py-1">
                      <div className="p-2.5 rounded-xl bg-white border border-[#D8ECD6] shadow-xs space-y-1.5">
                        <div className="flex items-center justify-between text-[11px] text-[#4E5E54] font-medium">
                          <span className="flex items-center space-x-1">
                            <Navigation className="w-3 h-3 text-[#22A45D]" />
                            <span>Route: {act.name} &rarr; {nextAct.name}</span>
                          </span>
                        </div>
                        <TrafficBadge 
                          origin={`${act.name}, ${plan.meta.location}`} 
                          destination={`${nextAct.name}, ${plan.meta.location}`} 
                          compact={false} 
                        />
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Right 1 Col: Day Cost Breakdown & Smart Advisory */}
        <div className="space-y-6">
          
          {/* Day Cost Breakdown Card */}
          <div className="glass-panel bg-white p-5 rounded-2xl space-y-4 border border-[#D8ECD6]">
            <h3 className="text-sm font-extrabold text-[#1A2E22] uppercase tracking-wider flex items-center space-x-2">
              <IndianRupee className="w-4 h-4 text-[#22A45D]" />
              <span>Day {activeDay} Budget Breakdown</span>
            </h3>

            <div className="space-y-2.5 text-xs">
              <div className="flex justify-between items-center text-[#4E5E54] pb-1.5 border-b border-[#D8ECD6]">
                <span>Monument & Activities:</span>
                <span className="font-mono font-bold text-[#1A2E22]">₹{currentDayData.costBreakdown.activities}</span>
              </div>
              <div className="flex justify-between items-center text-[#4E5E54] pb-1.5 border-b border-[#D8ECD6]">
                <span>Food & Street Eats:</span>
                <span className="font-mono font-bold text-[#1A2E22]">₹{currentDayData.costBreakdown.food}</span>
              </div>
              <div className="flex justify-between items-center text-[#4E5E54] pb-1.5 border-b border-[#D8ECD6]">
                <span>Hotel / Stay Allocation:</span>
                <span className="font-mono font-bold text-[#1A2E22]">₹{currentDayData.costBreakdown.stay}</span>
              </div>
              <div className="flex justify-between items-center text-[#4E5E54] pb-1.5 border-b border-[#D8ECD6]">
                <span>Local Rickshaw / Transit:</span>
                <span className="font-mono font-bold text-[#1A2E22]">₹{currentDayData.costBreakdown.localTransport}</span>
              </div>
              <div className="flex justify-between items-center text-sm pt-2 text-[#1D8E50] font-bold">
                <span>Total Day Estimate:</span>
                <span className="font-mono font-extrabold text-[#1A2E22]">₹{currentDayData.costBreakdown.totalDayCost}</span>
              </div>
            </div>
          </div>

          {/* Smart Tips & IoT Live Link */}
          <div className="glass-panel bg-white p-5 rounded-2xl space-y-3 border border-[#B8E4B5]">
            <h3 className="text-sm font-bold text-[#1A2E22] flex items-center space-x-2">
              <Sparkles className="w-4 h-4 text-[#22A45D]" />
              <span>Smart Travel Advisories</span>
            </h3>
            <ul className="space-y-2.5 text-xs text-[#4E5E54]">
              {plan.smartTips.map((tip, i) => (
                <li key={i} className="leading-relaxed bg-[#F4FBF3] p-2.5 rounded-xl border border-[#D8ECD6] font-medium">
                  {tip}
                </li>
              ))}
            </ul>

            <Link
              to="/crowd"
              className="mt-3 w-full py-2.5 rounded-xl bg-[#E8F8ED] hover:bg-[#D8ECD6] text-[#1D8E50] text-xs font-bold flex items-center justify-center space-x-1.5 border border-[#BDE8C7] transition-colors"
            >
              <Activity className="w-3.5 h-3.5 text-[#22A45D]" />
              <span>Check Live Spot Footfall</span>
            </Link>

            <p className="text-[10px] text-[#718778] text-center font-medium leading-tight pt-1">
              ⚡ Live IoT crowd sensing shown for our Jaipur pilot zone — full-city rollout in progress.
            </p>
          </div>

        </div>

      </div>

    </div>
  );
}
